### ISSUE TITLE
Cuda Compile Error

### ISSUE THREAD

**Issue by dennisushi** [rosalindfranklininstitute/cuda-slic#2]
Hi, when running the code as shown in the READEME, I get the following:

```bash
CompileError: nvcc compilation of /tmp/tmp1sjxj8vx/kernel.cu failed
[command: nvcc --cubin -std=c++11 -arch sm_86 -I/home/dennisushi/.local/lib/python3.6/site-packages/pycuda/cuda kernel.cu]
[stderr: nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture']
```

FYI, for me FastSLIC (https://github.com/Algy/fast-slic) works and I use NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2

**Comment by abonawas** [comment]
Hi Dennis,

PyCUDA tries to compile .cu files with the latest architecture that your gpu support https://github.com/inducer/pycuda/blob/4d97ad973d29f86a65f2fdfde05ec820927b7acf/pycuda/compiler.py#L246.
This could be because you're running an old nvcc. I recommend installing the cudatoolkit and using the nvcc executable that comes with it.
If you want to force the options that PyCUDA uses, you can set the environment variable like this:
`export DEFAULT_NVCC_FLAGS='-arch sm_35'`
look up the computing compatibility of your GPU that determiners what sm_xx you should use.
